openapi: 3.0.1
info:
  title: Book API
  description: Book API Specification
  version: 0.0.1
servers:
  - url: /
paths:
  /api/v1/books/{bookId}:
    get:
      tags:
        - book
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Books'
  /api/v1/books:
    get:
      tags:
        - books
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 1000
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Books'
components:
  schemas:
    Books:
      type: object
      properties:
        bookId:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        author:
          type: string
        year:
          type: integer
          format: int64
        publishedAt:
          type: string
          format: date-time
